travis:
  secure:
    BINSTAR_TOKEN: EVD/p6sgTrgazgx0HSo8NMwwPuecclvkwpqsPiRuB/4yRPiR4kocFbK2yEyMEF/8AeA/rgQBSwT0UqpvyeXk/q9FnCaVXCWW7tXP0lDLj615cLGpwl6d8Nz0PGC9N+tJPYhT5bAHBx4PR1Bw5sxrHCFjI0DZpRKE+JuS4amhIcn0cR8VEuUxTBP53uCQg/zK+cu0v1XmdNwmZwUqTmz+2SMSjj1MuhyamJSdyHHGZM3NqVz0WD6/aqCIhUMmy1Gl9NSjV7aQqbR+cCFHXM4anegu7BNoEa7rU9pIssguLUa4E6Cdp2fZlyPdPnm4dWz05LBupqVaGNYmkjw1l6g4nBSbByib0XdT5+y5ZCBAF1fCCapDiXzkuR+AccCup66epIM+QUyZUHdNuh73nJAjEmsGG0EPjqSn9pzcvUUwsp+kTuIhABMPDUc638Fcqfz7xNT9/r1rkeo0HjpCfboNrxeuBquFoRHllYlWLaSnWJVLLf8FOuUwg7lNxHkdaso++jN1fmHR9WM47lU4kWckRnXB1YaPIbvUEd+NV/RSLokeFvp61GYe7N7w6xclLd0tQPqnkgkF4LBNTiaaKtM9tec7YJkdgoJc5+4zsU6/zwB7vvuS+nw8NM1kVmWaKJCVGLPP0Mich8snFcJNy5Yu9DVXGlg0HPaR9Kzh7QnW320=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
