travis:
  secure:
    BINSTAR_TOKEN: W+D2YGZK5WXBoF7rSDaAjNitGXMyM/Och8PX25x51hB8KUPz5SQo9cMDFkxZWnXfYQ4B3taClF3YMjAbXR2C5Pv1NzhorrQ/Bxifl1ScUnQUKPt/anVqxVw0zC7cLeUpETAWQKQRbtZ1cPKSIwZSp6f0DNQazIuztAYVNyYXbZMSdu89Z5/2+nNZ9BB2q87fijZxGRnWlhifehURFDfKNdtUn7yJKfWEMR9CaOu/dA2bSFX7Wmn0kzZ1L5djH0tA8qGSblHzR3DuIClIjL8A9dl3HhRUS6aIkmYuysJ297+Vq9jVrHRi2U/TsdsYDWaxHIqXlH7iKyzF5AzNjqe5Mqq6FIawvkyh2uAwQgpQAkvVSXO3956VntEm1TmKlbi4bAauqQ7rrqhKeWQ9scYPBS9DwrfqfhuIqW4spUOPBsJvFin4LR3hLiCBcbdCr4tqNWEKynKLppo6wVo38aOD2fcHfbPkRWfY6OGH0zD8Uwiy+6kG0c31FKixmjzIeBXnitlkj0s7lKiDwiQlBM5ZNy6MjS65Y8lmwqM2zpjgozI37HwXPH+OymWlWkgCsO5znZTooIqQPuSnU5oCBW6af4uvpkmE8spXJ/AbOe3QEzaK/3V6eYVIMWyMr+6tK29k9yib+L3abjoyZQYDM9juDVgTTP5MZQkcpBLwKFgp9qc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
